// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbxnndsqgscxamvlxloh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieG5uZHNxZ3NjeGFtdmx4bG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDc3NDksImV4cCI6MjA2ODUyMzc0OX0.hlL4xTqU5DYJS8IklJj2H4DyKvRpBGc4L2YxwNWAx1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});